# Generated by Django 5.2.7 on 2025-10-04 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=100)),
                ("other_names", models.CharField(max_length=200)),
                ("id_passport", models.CharField(max_length=50, unique=True)),
                (
                    "phone",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+?1?\\d{9,15}$"
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ethnicity", models.CharField(blank=True, max_length=100, null=True)),
                ("religion", models.CharField(blank=True, max_length=100, null=True)),
                ("dob", models.DateField()),
                (
                    "special_interest",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Youth", "Youth"),
                            ("Women", "Women"),
                            ("PWD", "PWD"),
                        ],
                        max_length=20,
                    ),
                ),
                ("county", models.CharField(max_length=100)),
                ("constituency", models.CharField(max_length=100)),
                ("ward", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "polling_station",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("diaspora", models.CharField(blank=True, max_length=100, null=True)),
                ("embassy", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "membership_category",
                    models.CharField(
                        choices=[
                            ("Ordinary Membership", "Ordinary Membership"),
                            ("Bronze Membership", "Bronze Membership"),
                            ("Life Membership", "Life Membership"),
                            ("Associate Membership", "Associate Membership"),
                            ("Group Membership", "Group Membership"),
                            ("Honorary Membership", "Honorary Membership"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "membership_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "certificate",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
                ),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
                "ordering": ["-registration_date"],
            },
        ),
        migrations.CreateModel(
            name="MembershipCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50, unique=True)),
                ("last_number", models.IntegerField(default=0)),
            ],
        ),
    ]
